[project]
name = "playgresql"
version = "0.1.0"
description = "PostgreSQL extensions testing with Django"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "ollama>=0.6.1",
    "pgvector>=0.4.1",
    "psycopg[binary]>=3.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
